services:
  - type: web
    name: isewr-frontend
    env: static
    buildCommand: bash build.sh
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true
    envVars:
      - key: REACT_APP_SUPABASE_URL
        sync: false
      - key: REACT_APP_SUPABASE_KEY
        sync: false
      - key: REACT_APP_BACKEND_URL
        value: https://isewr-backend.onrender.com
      - key: GENERATE_SOURCEMAP
        value: false
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 