import React, { useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';

const Home = () => {
  const navigate = useNavigate();
  const heroRef = useRef(null);
  const aiCardRef = useRef(null);
  
  // Add 3D hover effect
  useEffect(() => {
    const handleMouseMove = (e) => {
      if (heroRef.current) {
        const { left, top, width, height } = heroRef.current.getBoundingClientRect();
        const x = (e.clientX - left) / width - 0.5;
        const y = (e.clientY - top) / height - 0.5;
        
        heroRef.current.style.transform = `perspective(1000px) rotateY(${x * 5}deg) rotateX(${-y * 5}deg)`;
      }
      
      if (aiCardRef.current) {
        const { left, top, width, height } = aiCardRef.current.getBoundingClientRect();
        const x = (e.clientX - left) / width - 0.5;
        const y = (e.clientY - top) / height - 0.5;
        
        aiCardRef.current.style.transform = `perspective(1000px) rotateY(${x * 25}deg) rotateX(${-y * 15}deg) translateZ(20px)`;
      }
    };
    
    document.addEventListener('mousemove', handleMouseMove);
    return () => document.removeEventListener('mousemove', handleMouseMove);
  }, []);

  const features = [
    { 
      title: 'Image Recognition', 
      path: '/recognition', 
      description: 'Upload an image to recognize objects',
      icon: '🔍',
      color: 'bg-blue-500'
    },
    { 
      title: 'Deep Fake Detection', 
      path: '/deepfake', 
      description: 'Check if a image is real or fake',
      icon: '🕵️',
      color: 'bg-purple-500'
    },
    { 
      title: 'AI Image Detection', 
      path: '/ai-detection', 
      description: 'Detect if an image was generated by AI',
      icon: '🤖',
      color: 'bg-yellow-500'
    },
    { 
      title: 'Image Processing', 
      path: '/processing', 
      description: 'Edit and enhance your images',
      icon: '🖼️',
      color: 'bg-green-500'
    },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-50 to-gray-100 py-12 px-4 sm:px-6 lg:px-8 overflow-hidden">
      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-16">
          <div 
            ref={heroRef}
            className="transition-transform duration-300 ease-out"
            style={{ transformStyle: 'preserve-3d' }}
          >
            <h1 className="text-6xl font-bold text-gray-800 mb-4 relative" style={{ transform: 'translateZ(50px)' }}>
              Lens<span className="text-yellow-500">Lynx</span>
            </h1>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto relative" style={{ transform: 'translateZ(30px)' }}>
              Advanced AI-powered tools for image recognition, analysis, and enhancement.
            </p>
            <div className="absolute -inset-20 bg-gradient-to-r from-yellow-100 to-blue-100 rounded-full blur-3xl opacity-30 -z-10"></div>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 mb-16">
          {features.map((feature, index) => (
            <div 
              key={index}
              className="bg-white rounded-xl shadow-lg overflow-hidden border border-gray-100 hover:shadow-xl hover:-translate-y-2 transition-all duration-300 cursor-pointer"
              onClick={() => navigate(feature.path)}
              style={{ transformStyle: 'preserve-3d' }}
            >
              <div className={`h-2 ${feature.color}`}></div>
              <div className="p-6">
                <div className="text-4xl mb-4 transform hover:scale-110 transition-transform duration-300">{feature.icon}</div>
                <h2 className="text-xl font-medium text-gray-800 mb-2">{feature.title}</h2>
                <p className="text-gray-500">{feature.description}</p>
              </div>
            </div>
          ))}
        </div>

        <div className="bg-white rounded-xl shadow-lg overflow-hidden border border-gray-100 p-8 mb-16 transform hover:shadow-xl transition-all duration-300">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
            <div>
              <h2 className="text-3xl font-bold text-gray-800 mb-4">Powerful AI Tools</h2>
              <p className="text-gray-600 mb-6">
                LensLynx provides cutting-edge AI technology for image analysis and processing. Our tools help you recognize objects, detect deepfakes, identify AI-generated images, and enhance your photos with advanced processing capabilities.
              </p>
              <div className="flex flex-wrap gap-4">
                <button 
                  onClick={() => navigate('/recognition')}
                  className="bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white px-6 py-3 rounded-lg font-medium transition-colors duration-200 shadow-md hover:shadow-lg transform hover:-translate-y-1"
                >
                  Get Started
                </button>
                <button 
                  onClick={() => navigate('/documentation')}
                  className="bg-gradient-to-r from-gray-100 to-gray-200 hover:from-gray-200 hover:to-gray-300 text-gray-800 px-6 py-3 rounded-lg font-medium transition-colors duration-200 shadow-md hover:shadow-lg transform hover:-translate-y-1"
                >
                  Learn More
                </button>
              </div>
            </div>
            <div className="flex justify-center perspective-1000">
              <div 
                ref={aiCardRef}
                className="w-72 h-72 relative transition-transform duration-300"
                style={{ transformStyle: 'preserve-3d' }}
              >
                {/* 3D Card with layers */}
                <div className="absolute inset-0 bg-gradient-to-br from-blue-600 to-purple-700 rounded-xl shadow-2xl flex flex-col items-center justify-center p-6"
                     style={{ transform: 'translateZ(0px)' }}>
                  <div className="bg-white/10 backdrop-blur-sm w-full h-full rounded-lg absolute"></div>
                  <div className="absolute top-3 left-3 right-3 h-1 bg-white/30 rounded-full"></div>
                  <div className="absolute bottom-3 left-3 right-3 h-1 bg-black/20 rounded-full"></div>
                  <div className="text-8xl mb-4 text-white drop-shadow-lg" style={{ transform: 'translateZ(40px)' }}>🤖</div>
                  <h3 className="text-2xl font-bold text-white drop-shadow-lg mb-2" style={{ transform: 'translateZ(30px)' }}>AI Powered</h3>
                  <p className="text-white/90 text-center text-sm" style={{ transform: 'translateZ(20px)' }}>
                    Advanced algorithms processing your images in real-time
                  </p>

                  {/* Decorative elements to enhance 3D effect */}
                  <div className="absolute -top-2 -right-2 w-8 h-8 bg-yellow-400 rounded-full" style={{ transform: 'translateZ(15px)' }}></div>
                  <div className="absolute -bottom-3 -left-3 w-10 h-10 bg-blue-300 rounded-full" style={{ transform: 'translateZ(10px)' }}></div>
                  
                  {/* Light reflections */}
                  <div className="absolute inset-0 bg-gradient-to-tr from-transparent to-white/20 rounded-xl"></div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="text-center">
          <h2 className="text-3xl font-bold text-gray-800 mb-8">Why Choose LensLynx?</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="bg-white p-6 rounded-xl shadow-md border border-gray-100 hover:shadow-xl hover:-translate-y-2 transition-all duration-300">
              <div className="text-3xl mb-4 transform hover:scale-110 transition-transform duration-300">🚀</div>
              <h3 className="text-xl font-medium text-gray-800 mb-2">Fast Processing</h3>
              <p className="text-gray-500">Our AI algorithms process your media quickly and efficiently.</p>
            </div>
            <div className="bg-white p-6 rounded-xl shadow-md border border-gray-100 hover:shadow-xl hover:-translate-y-2 transition-all duration-300">
              <div className="text-3xl mb-4 transform hover:scale-110 transition-transform duration-300">🔒</div>
              <h3 className="text-xl font-medium text-gray-800 mb-2">Secure & Private</h3>
              <p className="text-gray-500">Your data is processed securely and never stored without permission.</p>
            </div>
            <div className="bg-white p-6 rounded-xl shadow-md border border-gray-100 hover:shadow-xl hover:-translate-y-2 transition-all duration-300">
              <div className="text-3xl mb-4 transform hover:scale-110 transition-transform duration-300">💡</div>
              <h3 className="text-xl font-medium text-gray-800 mb-2">Advanced Technology</h3>
              <p className="text-gray-500">Powered by state-of-the-art AI models for accurate results.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home; 